global:
  scrape_interval: 15s # How frequently to scrape targets
  scrape_timeout: 10s  # Timeout for scrapes
  evaluation_interval: 15s # How frequently to evaluate rules

scrape_configs:
  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['mysqld_exporter:9104'] # The hostname is the service name, port is the exporter's default

  # Uncomment and configure if your Node.js app also exposes Prometheus metrics
  # - job_name: 'nodejs_app'
  #   metrics_path: '/metrics' # Or whatever path your Node.js app exposes metrics on
  #   static_configs:
  #     - targets: ['app:5000']
