apiVersion: apps/v1
kind: Deployment
metadata:
  name: lawhelp-app
  namespace: lawhelp
  labels:
    app: lawhelp
    tier: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lawhelp
      tier: application
  template:
    metadata:
      labels:
        app: lawhelp
        tier: application
    spec:
      containers:
      - name: lawhelp
        image: lawhelp:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: lawhelp-secrets
              key: jwt-secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: lawhelp-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always