---
- name: Install LawHelp Application Dependencies
  hosts: lawhelp_servers
  become: yes
  vars:
    node_version: "20.x"
    app_user: "lawhelp"
    app_directory: "/opt/lawhelp"
    
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install system dependencies
      apt:
        name:
          - curl
          - wget
          - gnupg2
          - software-properties-common
          - build-essential
          - git
          - nginx
          - mysql-server
          - python3-pymysql
        state: present

    - name: Add NodeSource repository key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource repository
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main"
        state: present

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Create application user
      user:
        name: "{{ app_user }}"
        system: yes
        shell: /bin/bash
        home: "{{ app_directory }}"
        create_home: yes

    - name: Create application directory
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    - name: Configure MySQL
      mysql_user:
        name: lawhelp_user
        password: "{{ mysql_password }}"
        priv: "lawhelp_db.*:ALL"
        state: present
      vars:
        mysql_password: "{{ vault_mysql_password }}"

    - name: Create MySQL database
      mysql_db:
        name: lawhelp_db
        state: present

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/lawhelp
        backup: yes
      notify: restart nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/lawhelp
        dest: /etc/nginx/sites-enabled/lawhelp
        state: link
      notify: restart nginx

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: Configure firewall
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - "22"
        - "80"
        - "443"
        - "5000"

    - name: Enable firewall
      ufw:
        state: enabled

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes